;;; config.el --- storax-powerline layer config file for Spacemacs.
;;
;; Copyright (c) 2012-2016 Sylvain Benner & Contributors
;;
;; Author: David Zuber <zuber.david@gmx.de>
;; URL: https://github.com/syl20bnr/spacemacs
;;
;; This file is not part of GNU Emacs.
;;
;;; License: GPLv3

;;; Commentary:

;;; Code:

(mode-icons-define-font "github-octicons")
(mode-icons-define-font "font-mfizz")
(mode-icons-define-font "FontAwesome")
(mode-icons-define-font "IcoMoon-Free")
(mode-icons-define-font "icomoon")
(mode-icons-define-font "Sauce Code Pro")

(defcustom mode-icons
  `((" Golden" "golden" xpm) ;; Icon created by Arthur Shlain from Noun Project
    (" Pulls" #xf092 FontAwesome)
    (" Rbow" "rainbow" xpm)
    (" hs" "hs" xpm)
    (" yas" "yas" xpm)
    ("AHK" "autohotkey" xpm)
    ("ARev" #xf021 FontAwesome)
    ("BibTeX" "bibtex" xpm)
    ("C/l" #xf107 font-mfizz)
    ("C?Perl" #xf148 font-mfizz)
    ("CSS" "css" xpm)
    ("C[#]/l" #xf10d font-mfizz)
    ("C[+][+]/l" #xf10c font-mfizz)
    ("Calc\\(ulator\\)?" #xf1ec FontAwesome)
    ("Calendar" #xf073 FontAwesome)
    ("Clojure" #xf10a font-mfizz)
    ("Coffee" "coffee" xpm)
    ("Compilation" "compile" xpm)
    ("Custom" #xf013 FontAwesome)
    ("Debug.*" #xf188 FontAwesome)
    ("Debug.*" #xf188 FontAwesome)
    ("ESS\\[BUGS\\]" #xf188 FontAwesome)
    ("ESS\\[SAS\\]" "sas" xpm)
    ("ESS\\[S\\]" "R" xpm)
    ("Elixir" #xf115 font-mfizz)
    ("Emacs-Lisp" "emacs" xpm)
    ("Erlang" #xf116 font-mfizz)
    ("HTML" "html" xpm)
    ("Haml" "haml" xpm)
    ("Haskell" #xf126 font-mfizz)
    ("Help" #xf059 FontAwesome)
    ("Image[imagemagick]" "svg" xpm)
    ("Inf-Ruby" "infruby" xpm)
    ("Info" #xf05a FontAwesome)
    ("Java/l" #xf12b font-mfizz)
    ("JavaScript" "js" xpm)
    ("Lisp Interaction" "emacs" xpm)
    ("Lisp" "cl" xpm)
    ("Magit" #xf1d2 FontAwesome)
    ("Markdown" #xf0c9 github-octicons)
    ("Narrow" #xf066 FontAwesome)
    ("Octave" "octave" xpm)
    ("Org" "org" xpm)
    ("PHP" "php" xpm)
    ("PHP/l" "php" xpm)
    ("Projectile Rails Server" "rails" xpm)
    ("Python" "python" xpm)
    ("Ruby" "ruby" xpm)
    ("SCSS" "sass" xpm)
    ("Sass" "sass" xpm)
    ("Scala" #xf15b font-mfizz)
    ("Scheme" "scheme" xpm)
    ("Shell-script" "bash" xpm)
    ("Slim" "slim" xpm)
    ("Snippet" "yas" xpm)
    ("Term" "term" xpm)
    ("Text\\'" #xf0f6 FontAwesome)
    ("Web" "html" xpm)
    ("WoMan" #xf05a FontAwesome)
    ("XML" "xml" xpm)
    ("YAML" "yaml" xpm)
    ("YASnippet" "yas" xpm)
    ("Zip-Archive" #xf1c6 FontAwesome)
    ("\\` ?company\\'" #xf1ad FontAwesome)
    ("\\`Go\\'" "go" xpm)
    ("iESS" "R" xpm)
    ("nXML" "xml" xpm)

    (apple #xf179 FontAwesome)
    (modified-outside #xf071 FontAwesome)
    (read-only #xf023 FontAwesome)
    (save #xf0c7 FontAwesome)
    (saved "" nil)
    (steal #xf21b FontAwesome)
    (undecided #xf128 FontAwesome)
    (unix #xeabd IcoMoon-Free)  ;; Clear Tux (Unlike FontAwesome)
    (unix #xf166 font-mfizz)    ;; Use ubuntu, since I think it is the most common.
    (unix #xf17c FontAwesome) ;; Fall Back to FontAwesome
    (win #xf17a FontAwesome)
    (writable #xf09c FontAwesome)
    ;; FIXME: use lsb_release to determine Linux variant and choose appropriate icon
    ;; This icon is clearer than FontAwesome's Linux Penguin
    ;; Diminished modes
    ("\\(?:ElDoc\\|Anzu\\|SP\\|Guide\\|PgLn\\|Undo-Tree\\|Ergo.*\\|,\\|Isearch\\|Ind\\|Fly\\)" nil nil))
  "Icons for majoppr and minor modes.

Each specificatioun is a list with the first element being the
name of the major mode.  The second the name of the icon file,
without the extension.  And the third being the type of icon."
  :type '(repeat
          (list (choice
                 (string :tag "Regular Expression")
                 (const :tag "Read Only Indicator" read-only)
                 (const :tag "Writable Indicator" writable)
                 (const :tag "Saved" saved)
                 (const :tag "Save" save)
                 (const :tag "Modified Outside Emacs" modified-outside)
                 (const :tag "Locked By Someone Else" steal)
                 (const :tag "Apple" apple)
                 (const :tag "Windows" win)
                 (const :tag "Unix" unix))
                (choice
                 (string :tag "Icon Name")
                 (integer :tag "Font Glyph Code")
                 (const :tag "Suppress" nil))
                (choice
                 (const :tag "text" nil)
                 (const :tag "Octicons" github-octicons)
                 (const :tag "Fizzed" font-mfizz)
                 (const :tag "Font Awesome" FontAwesome)
                 (const :tag "Ico Moon Free" IcoMoon-Free)
                 (const :tag "png" png)
                 (const :tag "gif" gif)
                 (const :tag "jpeg" jpeg)
                 (const :tag "jpg" jpg)
                 (const :tag "xbm" xbm)
                 (const :tag "xpm" xpm))))
  :group 'mode-icons)

(defcustom font-icons
  (list (cons "line_number" (char-to-string #xe0a1))
        (cons "column_number" (char-to-string #xe0a3))
        (cons "lock" (char-to-string #xe0a2))
        (cons "pl_l_flame_b" (char-to-string #xe0c0))
        (cons "pl_l_flame_w" (char-to-string #xe0c1))
        (cons "pl_r_flame_b" (char-to-string #xe0c2))
        (cons "pl_r_flame_w" (char-to-string #xe0c3))
        (cons "pl_l_pixels" (char-to-string #xe0c4))
        (cons "pl_r_pixels" (char-to-string #xe0c5))
        (cons "pl_l_pixels_big" (char-to-string #xe0c6))
        (cons "pl_r_pixels_big" (char-to-string #xe0c7))
        (cons "package" (char-to-string #xf0c4))
        (cons "android" (char-to-string #xe70e))
        (cons "angular" (char-to-string #xe753))
        (cons "appcelerator" (char-to-string #xe7ab))
        (cons "apple" (char-to-string #xe711))
        (cons "appstore" (char-to-string #xe713))
        (cons "aptana" (char-to-string #xe799))
        (cons "asterisk" (char-to-string #xe7ac))
        (cons "atlassian" (char-to-string #xe75b))
        (cons "atom" (char-to-string #xe764))
        (cons "aws" (char-to-string #xe7ad))
        (cons "backbone" (char-to-string #xe752))
        (cons "bing_small" (char-to-string #xe700))
        (cons "bintray" (char-to-string #xe794))
        (cons "bitbucket" (char-to-string #xe703))
        (cons "blackberry" (char-to-string #xe723))
        (cons "bootstrap" (char-to-string #xe747))
        (cons "bower" (char-to-string #xe74d))
        (cons "brackets" (char-to-string #xe79d))
        (cons "bugsense" (char-to-string #xe78d))
        (cons "celluloid" (char-to-string #xe76b))
        (cons "chrome" (char-to-string #xe743))
        (cons "cisco" (char-to-string #xe765))
        (cons "clojure" (char-to-string #xe768))
        (cons "clojure_alt" (char-to-string #xe76a))
        (cons "cloud9" (char-to-string #xe79f))
        (cons "coda" (char-to-string #xe793))
        (cons "code" (char-to-string #xe796))
        (cons "code_badge" (char-to-string #xe7a3))
        (cons "codeigniter" (char-to-string #xe780))
        (cons "codepen" (char-to-string #xe716))
        (cons "codrops" (char-to-string #xe72f))
        (cons "coffeescript" (char-to-string #xe751))
        (cons "compass" (char-to-string #xe761))
        (cons "composer" (char-to-string #xe783))
        (cons "creativecommons" (char-to-string #xe789))
        (cons "creativecommons_badge" (char-to-string #xe78a))
        (cons "css3" (char-to-string #xe749))
        (cons "css3_full" (char-to-string #xe74a))
        (cons "css_tricks" (char-to-string #x701))
        (cons "cssdeck" (char-to-string #xe72a))
        (cons "dart" (char-to-string #xe798))
        (cons "database" (char-to-string #xe706))
        (cons "debian" (char-to-string #xe77d))
        (cons "digital-ocean" (char-to-string #xe7ae))
        (cons "django" (char-to-string #xe71d))
        (cons "dlang" (char-to-string #xe7af))
        (cons "docker" (char-to-string #xe7b0))
        (cons "doctrine" (char-to-string #xe774))
        (cons "dojo" (char-to-string #xe71c))
        (cons "dotnet" (char-to-string #xe77f))
        (cons "dreamweaver" (char-to-string #xe79c))
        (cons "dropbox" (char-to-string #xe707))
        (cons "drupal" (char-to-string #xe742))
        (cons "eclipse" (char-to-string #xe79e))
        (cons "ember" (char-to-string #xe71b))
        (cons "envato" (char-to-string #xe75d))
        (cons "erlang" (char-to-string #xe7b1))
        (cons "extjs" (char-to-string #xe78e))
        (cons "firebase" (char-to-string #xe787))
        (cons "firefox" (char-to-string #xe745))
        (cons "fsharp" (char-to-string #xe7a7))
        (cons "ghost" (char-to-string #xe71f))
        (cons "ghost_small" (char-to-string #xe714))
        (cons "git" (char-to-string #xe702))
        (cons "git_branch" (char-to-string #xe725))
        (cons "git_commit" (char-to-string #xe729))
        (cons "git_compare" (char-to-string #xe728))
        (cons "git_merge" (char-to-string #xe727))
        (cons "git_pull_request" (char-to-string #xe726))
        (cons "github" (char-to-string #xe709))
        (cons "github_alt" (char-to-string #xe708))
        (cons "github_badge" (char-to-string #xe70a))
        (cons "github_full" (char-to-string #xe717))
        (cons "gnu" (char-to-string #xe779))
        (cons "go" (char-to-string #xe724))
        (cons "google-cloud-platform" (char-to-string #xe7b2))
        (cons "google_drive" (char-to-string #xe731))
        (cons "grails" (char-to-string #xe7b3))
        (cons "groovy" (char-to-string #xe775))
        (cons "grunt" (char-to-string #xe74c))
        (cons "gulp" (char-to-string #xe763))
        (cons "hackernews" (char-to-string #xe71a))
        (cons "haskell" (char-to-string #xe777))
        (cons "heroku" (char-to-string #xe77b))
        (cons "html5" (char-to-string #xe736))
        (cons "html5_3d_effects" (char-to-string #xe735))
        (cons "html5_connectivity" (char-to-string #xe734))
        (cons "html5_device_access" (char-to-string #xe733))
        (cons "html5_multimedia" (char-to-string #xe732))
        (cons "ie" (char-to-string #xe744))
        (cons "illustrator" (char-to-string #xe7b4))
        (cons "intellij" (char-to-string #xe7b5))
        (cons "ionic" (char-to-string #xe7a9))
        (cons "java" (char-to-string #xe738))
        (cons "javascript" (char-to-string #xe74e))
        (cons "javascript_badge" (char-to-string #xe781))
        (cons "javascript_shield" (char-to-string #xe74f))
        (cons "jekyll_small" (char-to-string #xe70d))
        (cons "jenkins" (char-to-string #xe767))
        (cons "jira" (char-to-string #xe75c))
        (cons "joomla" (char-to-string #xe741))
        (cons "jquery" (char-to-string #xe750))
        (cons "jquery_ui" (char-to-string #xe754))
        (cons "komodo" (char-to-string #xe792))
        (cons "krakenjs" (char-to-string #xe785))
        (cons "krakenjs_badge" (char-to-string #xe784))
        (cons "laravel" (char-to-string #xe73f))
        (cons "less" (char-to-string #xe758))
        (cons "linux" (char-to-string #xe712))
        (cons "magento" (char-to-string #xe740))
        (cons "mailchimp" (char-to-string #xe79a))
        (cons "markdown" (char-to-string #xe73e))
        (cons "materializecss" (char-to-string #xe7b6))
        (cons "meteor" (char-to-string #xe7a5))
        (cons "meteorfull" (char-to-string #xe7a6))
        (cons "mitlicence" (char-to-string #xe78b))
        (cons "modernizr" (char-to-string #xe720))
        (cons "mongodb" (char-to-string #xe7a4))
        (cons "mootools" (char-to-string #xe790))
        (cons "mootools_badge" (char-to-string #xe78f))
        (cons "mozilla" (char-to-string #xe786))
        (cons "msql_server" (char-to-string #xe77c))
        (cons "mysql" (char-to-string #xe704))
        (cons "nancy" (char-to-string #xe766))
        (cons "netbeans" (char-to-string #xe79b))
        (cons "netmagazine" (char-to-string #xe72e))
        (cons "nginx" (char-to-string #xe776))
        (cons "nodejs" (char-to-string #xe719))
        (cons "nodejs_small" (char-to-string #xe718))
        (cons "npm" (char-to-string #xe71e))
        (cons "onedrive" (char-to-string #xe762))
        (cons "openshift" (char-to-string #xe7b7))
        (cons "opensource" (char-to-string #xe771))
        (cons "opera" (char-to-string #xe746))
        (cons "perl" (char-to-string #xe769))
        (cons "phonegap" (char-to-string #xe730))
        (cons "photoshop" (char-to-string #xe7b8))
        (cons "php" (char-to-string #xe73d))
        (cons "postgresql" (char-to-string #xe76e))
        (cons "prolog" (char-to-string #xe7a1))
        (cons "python" (char-to-string #xe73c))
        (cons "rackspace" (char-to-string #xe7b9))
        (cons "raphael" (char-to-string #xe75f))
        (cons "rasberry_pi" (char-to-string #xe722))
        (cons "react" (char-to-string #xe7ba))
        (cons "redhat" (char-to-string #xe7bb))
        (cons "redis" (char-to-string #xe76d))
        (cons "requirejs" (char-to-string #xe770))
        (cons "responsive" (char-to-string #xe797))
        (cons "ruby" (char-to-string #xe739))
        (cons "ruby_on_rails" (char-to-string #xe73b))
        (cons "ruby_rough" (char-to-string #xe791))
        (cons "rust" (char-to-string #xe7a8))
        (cons "safari" (char-to-string #xe748))
        (cons "sass" (char-to-string #xe74b))
        (cons "scala" (char-to-string #xe737))
        (cons "scriptcs" (char-to-string #xe7bc))
        (cons "scrum" (char-to-string #xe7a0))
        (cons "senchatouch" (char-to-string #xe78c))
        (cons "sizzlejs" (char-to-string #xe788))
        (cons "smashing_magazine" (char-to-string #xe72d))
        (cons "snap_svg" (char-to-string #xe75e))
        (cons "sqllite" (char-to-string #xe7c4))
        (cons "stackoverflow" (char-to-string #xe710))
        (cons "streamline" (char-to-string #xe705))
        (cons "stylus" (char-to-string #xe759))
        (cons "sublime" (char-to-string #xe7aa))
        (cons "swift" (char-to-string #xe755))
        (cons "symfony" (char-to-string #xe756))
        (cons "symfony_badge" (char-to-string #xe757))
        (cons "techcrunch" (char-to-string #xe72c))
        (cons "terminal" (char-to-string #xe795))
        (cons "terminal_badge" (char-to-string #xe7a2))
        (cons "travis" (char-to-string #xe77e))
        (cons "trello" (char-to-string #xe75a))
        (cons "typo3" (char-to-string #xe772))
        (cons "ubuntu" (char-to-string #xe73a))
        (cons "uikit" (char-to-string #xe773))
        (cons "unity_small" (char-to-string #xe721))
        (cons "vim" (char-to-string #xe7c5))
        (cons "visualstudio" (char-to-string #xe70c))
        (cons "w3c" (char-to-string #xe76c))
        (cons "webplatform" (char-to-string #xe76f))
        (cons "windows" (char-to-string #xe70f))
        (cons "wordpress" (char-to-string #xe70b))
        (cons "yahoo" (char-to-string #xe715))
        (cons "yahoo_small" (char-to-string #xe72b))
        (cons "yeoman" (char-to-string #xe77a))
        (cons "yii" (char-to-string #xe782))
        (cons "zend" (char-to-string #xe778)))
  "Font Icons."
  :type '(alist :value-type (group character))
  :group 'mode-icons)

(mode-icons-mode)

;;; config.el ends here
